// SPDX-License-Identifier: MIT

//Inspired by hash256.org
pragma solidity ^0.8.30;

import {ERC20} from "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";

contract HashToken is ERC20 {
    error HashToken__InvalidNonce();
    error HashToken__TimeRanOut();

    uint256 immutable TOKENS_PER_MINT;

    bytes32 public TARGET;
    uint256 public COUNTER;
    uint256 public TIME_UNTIL_MINING_IS_VALID;
    uint256 public TIMESTAMP;

    /*
    @param tokensPerMint - numbers of tokens per single mint
    @param miningTime - time during which minting is available
    @param initialTarget - target selected by deployer, pass 0 too be randomly selected. The higher the target - the easier is to mine.
    Do not pass arbitrary value unless you absolutely have to
    */
    constructor(
        string memory name,
        string memory symbol,
        uint256 tokensPerMint,
        uint256 miningTime,
        uint256 initialTarget
    ) ERC20(name, symbol) {
        TOKENS_PER_MINT = tokensPerMint;
        TIME_UNTIL_MINING_IS_VALID = miningTime;
        COUNTER = 1;
        TIMESTAMP = block.timestamp;
        if (initialTarget == 0) {
            TARGET = keccak256(abi.encodePacked(block.timestamp, block.prevrandao, msg.sender));
        } else {
            TARGET = bytes32(initialTarget);
        }
    }
    /*
    @dev function mint() takes nonce generated by your miner,takes address of sender,hashes it and checks if its lower than target
    Every 10th mint it also checks if enough time has elapsed and if mining is still open. Once time runs out function will revert any call
    */

    function mint(bytes32 nonce) external {
        if (COUNTER > 10) checkTime();
        if (uint256(keccak256(abi.encode(nonce, msg.sender))) > uint256(TARGET)) revert HashToken__InvalidNonce();

        _mint(msg.sender, TOKENS_PER_MINT);
        TARGET = keccak256(abi.encodePacked(block.timestamp, block.prevrandao, msg.sender));
        ++COUNTER;
    }

    /*
    @dev checks time every 10h mint.
    After enough time has passed this function will revert any call
    */
    function checkTime() internal {
        if ((TIMESTAMP + TIME_UNTIL_MINING_IS_VALID) < block.timestamp) {
            revert HashToken__TimeRanOut();
        } else {
            COUNTER = 1;
        }
    }

    function getCurrentTarget() public view returns (bytes32 currentTarget) {
        return TARGET;
    }

    function getCounterValue() public view returns (uint256 currentCounter) {
        return COUNTER;
    }

    function getTimeLeft() public view returns (uint256) {
        return (block.timestamp - (TIMESTAMP + TIME_UNTIL_MINING_IS_VALID));
    }
}
