// SPDX-License-Identifier: MIT

//Inspired by hash256.org
pragma solidity ^0.8.30;

import {ERC20} from "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";

contract HashToken is ERC20 {
    error HashToken__InvalidNonce();
    error HashToken__TimeRanOut();

    event SuccessfulMint(address);

    uint256 immutable TOKENS_PER_MINT;
    uint256 public immutable DIFFICULTY;

    uint256 public TARGET;
    uint256 public COUNTER;
    uint256 public MINING_TIMEFRAME;
    uint256 public TIMESTAMP;

    uint256[] public PREMINT_VALUES;
    address[] public REMINT_ADDRESSES;

    constructor(
        string memory name,
        string memory symbol,
        uint256 tokensPerMint,
        uint256 miningTime,
        uint256 initialTarget,
        uint256 difficultyAdjustment,
        uint256[] memory premintValues,
        address[] memory premintAddresses
    ) ERC20(name, symbol) {
        if (premintValues.length != premintAddresses.length) revert();
        for (uint256 i = 0; i < premintValues.length; i++) {
            _mint(premintAddresses[i], premintValues[i]);
        }
        TOKENS_PER_MINT = tokensPerMint;
        MINING_TIMEFRAME = miningTime;
        COUNTER = 1;
        TIMESTAMP = block.timestamp;
        if (difficultyAdjustment != 0) DIFFICULTY = difficultyAdjustment;
        else DIFFICULTY = 1e6;

        if (initialTarget == 0) {
            TARGET = uint256(keccak256(abi.encodePacked(block.timestamp, block.prevrandao, msg.sender, address(block.coinbase)))) / DIFFICULTY;
        } else {
            TARGET = initialTarget;
        }
    }
    /*
    @dev function mint() takes nonce generated by your miner,takes address of sender,hashes it and checks if its lower than target
    Every 10th mint it also checks if enough time has elapsed and if mining is still open. Once time runs out function will revert any call
    */

    function mint(bytes32 nonce) external {
        if (COUNTER > 10) checkTime();
        if (uint256(keccak256(abi.encode(nonce, msg.sender))) > TARGET) revert HashToken__InvalidNonce();

        _mint(msg.sender, TOKENS_PER_MINT);
        TARGET = uint256(keccak256(abi.encodePacked(block.timestamp, block.prevrandao, msg.sender, address(block.coinbase)))) / DIFFICULTY;
        ++COUNTER;
        emit SuccessfulMint(msg.sender);
    }

    /*
    @dev checks time every 10th mint.
    After enough time has passed this function will revert any call
    */
    function checkTime() internal {
        if ((TIMESTAMP + MINING_TIMEFRAME) < block.timestamp) {
            revert HashToken__TimeRanOut();
        } else {
            COUNTER = 1;
        }
    }

    function getCurrentTarget() public view returns (uint256) {
        return TARGET;
    }

    function getCounterValue() public view returns (uint256) {
        return COUNTER;
    }

    function getTimeLeft() public view returns (uint256) {
        if (block.timestamp >= TIMESTAMP + MINING_TIMEFRAME) {
            return 0;
        }

        return (TIMESTAMP + MINING_TIMEFRAME) - block.timestamp;
    }
}
